#! /bin/sh
xscreensaver -no-splash &

pgrep -x sxhkd > /dev/null || sxhkd &
nm-applet &
bspc monitor -d 1 2 3 4 5 6
tint2 &
bspc config border_width         2
bspc config window_gap          12
pnmixer &
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill ~/.wallpapers/234.jpg
xsetroot -cursor_name left_ptr &
wmname LG3D &
#~/.config/polybar/./launch.sh
bspc config focus_follows_pointer true
bspc config border_width 0
picom --experimental-backends &
